language: python

python:
  - 3.6

sudo: required
dist: trusty
addons:
  postgresql: "9.6"

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE="decide.settings"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "create user decide with password 'decide'" -U postgres
  - psql -c "create database decide owner decide" -U postgres

script:
  - python ./decide/manage.py migrate
  - python ./decide/manage.py test ./decide

notifications:
    email: false
    
branches:
    only:
    - master
    - develop

deploy:
  provider: heroku
  api_key: 51903f27-4bbc-44d9-91c7-036b37512b41
  app: decide-ganimedes-auth