language: python

python:
  - 3.6

sudo: required
dist: trusty
addons:
  postgresql: "9.6"

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE="decide.settings"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "create user decide with password 'decide'" -U postgres
  - psql -c "create database decide owner decide" -U postgres

script:
  - python ./decide/manage.py makemigrations
  - python ./decide/manage.py migrate
  - python ./decide/manage.py compilemessages
  - python ./decide/manage.py test ./decide
  - if [[ $TRAVIS_BRANCH == "master" ]]; then git archive --format zip --output ./decide.zip master; fi

before_deploy:
- git config --local user.name davigldom
- git config --local user.email davigldom@gmail.com
- export YEAR=`date +"%Y"`  
# - export GIT_TAG=v2.0.$TRAVIS_BUILD_NUMBER-$YEAR
- export GIT_TAG=v2.0.0-$YEAR
- git tag -a $GIT_TAG -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api-key:
    secure: DJu51MlITLZYIN4/JAiZClHneB2qzh/7uZTjRQvOHAc7lA4kWolGD640aMFZFhEaGfHRspbxqCDl3Wq8XRnhKrS7qVSBZ0r0jekg3LDXpbVobT32RLhjszJ/mEsOhXUtTppxNjNDwUpMIM+bSdOj6ngzlEsHmYZkPfEfoYF3zoIuGOQrCiF9jaHBKyNJPijBeeZG40gxVB4QgcNwZNvM1N0Ei2iwddoRAyUFvJGKWcwDNEilBLnPA54hDiY4D5wnNH69UWaxzpLda9DKybvQmpa3ilo7Qogk7+oGNN9ZOlKQVvGCebHZelwi2RSoeoqdgE1G1Sg/bAdN93QGTOFxbMkSNYjdg7CawSM7hEnM0PMyB/e16FPTvuScmsmThXHRXY0ivMEwQ3+KLo9d7A0KUUw0ebqQR45/73vhixpBhUrl+rxAYSQRwT9G02hyg7TbzB3uTR0i3XbprzCTSVuYbpOihLDsl42IJUs27cwvkA2hh9ORhky8m0G/g6eKGEAldcWzHvUDoWqYd13DV2B8ft0HByRobEKnGec/vnqn+3fgQw5mrPwCR+iHGYLS2A7O4WOehl1reNsW1qfdlRM+kj60u5cPCH8vnOvgTGuvTN3yr/JDNMf7L9qB5FhyoKx7seit2c5o+F5twmkHoWVRWcPAkDb57D4ud7pbf+rQOqM=
  file: "./decide.zip"
  skip_cleanup: true
  on:
    branch: master
    tags: false

notifications:
  email: false
    
branches:
  only:
  - master
  - develop
    